// Working customer live photo + signature capture for the static Identity page in index.html.
(()=>{
  const $=id=>document.getElementById(id); let stream=null, photoBlob=null, currentUser=null;
  const db=()=>window.sb || window.__sb;
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const msg=t=>{const e=$('identityMsg');if(e)e.textContent=t};
  async function getUser(){const client=db();if(!client)return null;const {data,error}=await client.auth.getUser();if(error)throw error;currentUser=data?.user||null;return currentUser}
  async function fillCustomers(){
    const sel=$('identityCustomer');if(!sel)return;
    try{const user=currentUser||await getUser();if(!user){sel.innerHTML='<option value="">Sign in first</option>';return}
      const {data,error}=await db().from('customers').select('id,full_name,phone').eq('created_by',user.id).order('created_at',{ascending:false});
      if(error)throw error;const rows=data||[];
      sel.innerHTML='<option value="">Select customer...</option>'+rows.map(c=>`<option value="${c.id}">${esc(c.full_name)} — ${esc(c.phone||'')}</option>`).join('');
      if(!rows.length)msg('No customers found. Create and save a customer under Customers & KYC first.');
    }catch(e){msg('Could not load customers: '+(e.message||e))}
  }
  async function startCamera(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access is not supported by this browser.');if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:1280},height:{ideal:720}},audio:false});const v=$('identityVideo');v.srcObject=stream;await v.play();msg('Camera ready. Position the customer and click Capture Photo.')}catch(e){msg('Camera permission/error: '+(e.message||e))}}
  function capturePhoto(){const v=$('identityVideo'),c=$('identityCanvas');if(!v?.srcObject||!v.videoWidth){msg('Start Camera first and allow camera permission.');return}c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0,c.width,c.height);c.toBlob(b=>{photoBlob=b;const p=$('photoPreview');p.src=URL.createObjectURL(b);p.classList.remove('hidden');msg('Photo captured. Retake if necessary.')},'image/jpeg',.9)}
  function retake(){photoBlob=null;$('photoPreview')?.classList.add('hidden');startCamera()}
  function initPad(){const c=$('signaturePad');if(!c||c.dataset.ready)return;c.dataset.ready='1';const ctx=c.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111';let drawing=false,last=null;const pos=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.addEventListener('pointerdown',e=>{e.preventDefault();c.setPointerCapture?.(e.pointerId);drawing=true;last=pos(e)});c.addEventListener('pointermove',e=>{if(!drawing)return;e.preventDefault();const p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p});c.addEventListener('pointerup',()=>{drawing=false;last=null});c.addEventListener('pointercancel',()=>{drawing=false;last=null});$('clearSignature').onclick=()=>ctx.clearRect(0,0,c.width,c.height)}
  function hasInk(){const c=$('signaturePad'),ctx=c.getContext('2d'),d=ctx.getImageData(0,0,c.width,c.height).data;for(let i=0;i<d.length;i+=4){if(d[i]<230||d[i+1]<230||d[i+2]<230)return true}return false}
  async function save(){const customerId=$('identityCustomer')?.value;if(!customerId)return msg('Select a customer first.');if(!photoBlob)return msg('Capture the customer photo first.');if(!hasInk())return msg('Sign in the signature box first.');const user=currentUser||await getUser();if(!user)return msg('Please sign in again.');try{msg('Saving photo and signature...');const base=`${user.id}/${customerId}`,stamp=Date.now(),photoPath=`${base}/photo-${stamp}.jpg`,sigPath=`${base}/signature-${stamp}.png`;let q=await db().storage.from('customer-identity').upload(photoPath,photoBlob,{contentType:'image/jpeg',upsert:false});if(q.error)throw q.error;const sigBlob=await new Promise(r=>$('signaturePad').toBlob(r,'image/png'));q=await db().storage.from('customer-identity').upload(sigPath,sigBlob,{contentType:'image/png',upsert:false});if(q.error)throw q.error;q=await db().from('customers').update({photo_path:photoPath,signature_path:sigPath,identity_captured_at:new Date().toISOString(),identity_captured_by:user.id}).eq('id',customerId).eq('created_by',user.id);if(q.error)throw q.error;msg('Customer photo and signature saved successfully.');if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}catch(e){msg('Could not save identity capture: '+(e.message||e))}}
  async function init(){try{currentUser=await getUser();fillCustomers();initPad();$('startCamera')?.addEventListener('click',startCamera);$('capturePhoto')?.addEventListener('click',capturePhoto);$('retakePhoto')?.addEventListener('click',retake);$('saveIdentity')?.addEventListener('click',save);document.querySelector('[data-page="identity"]')?.addEventListener('click',()=>setTimeout(fillCustomers,50));}catch(e){msg(e.message||'Unable to initialize identity capture.')}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));
})();
