// LoanAppraise Identity Capture v3 - reuse the application's authenticated Supabase session.
(()=>{
 const $=id=>document.getElementById(id); let stream=null,photoBlob=null,padReady=false;
 const message=t=>{const e=$('identityMsg');if(e)e.textContent=t};
 const client=()=>window.sb || window.__loanAppraiseClient || (window.supabase&&window.SUPABASE_URL&&window.SUPABASE_ANON_KEY?window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY):null);
 async function current(){const c=client();if(!c)throw Error('LoanAppraise is still loading. Please wait a moment.');const {data,error}=await c.auth.getSession();if(error)throw error;return data.session?.user||null}
 async function loadCustomers(){const s=$('identityCustomer');if(!s)return;try{const c=client();if(!c)return setTimeout(loadCustomers,300);const u=await current();if(!u){s.innerHTML='<option value="">Open this page after logging into LoanAppraise</option>';message('Your login session is not ready yet. Please wait...');return setTimeout(loadCustomers,800)}s.innerHTML='<option value="">Loading customers...</option>';const {data,error}=await c.from('customers').select('id,full_name,phone').eq('created_by',u.id).order('created_at',{ascending:false});if(error)throw error;const rows=data||[];s.innerHTML='<option value="">Select customer...</option>'+rows.map(x=>`<option value="${x.id}">${String(x.full_name||'').replace(/[<&]/g,m=>m==='<'?'&lt;':'&amp;')} — ${String(x.phone||'')}</option>`).join('');message(rows.length?'Select the customer whose photo and signature you want to capture.':'No customers found. Save a customer under Customers & KYC first.')}catch(e){message('Customer list error: '+(e.message||e));}}
 function signature(){const c=$('signaturePad');if(!c||padReady)return;padReady=true;const ctx=c.getContext('2d');ctx.lineWidth=4;ctx.lineCap='round';ctx.strokeStyle='#111';let down=false,last=null;const pos=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.addEventListener('pointerdown',e=>{e.preventDefault();down=true;last=pos(e);c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointermove',e=>{if(!down)return;e.preventDefault();const p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p});const stop=()=>{down=false;last=null};c.addEventListener('pointerup',stop);c.addEventListener('pointercancel',stop);$('clearSignature').onclick=()=>ctx.clearRect(0,0,c.width,c.height)}
 async function start(){try{if(!window.isSecureContext)throw Error('Camera requires the HTTPS app address.');if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera is not supported by this browser.');stream?.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:1280},height:{ideal:720}},audio:false});const v=$('identityVideo');v.srcObject=stream;await v.play();message('Camera ready. Click Capture Photo.')}catch(e){message('Camera error: '+(e.message||e))}}
 function capture(){const v=$('identityVideo'),c=$('identityCanvas');if(!v?.videoWidth)return message('Start Camera and allow permission first.');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0,c.width,c.height);c.toBlob(b=>{photoBlob=b;const p=$('photoPreview');p.src=URL.createObjectURL(b);p.classList.remove('hidden');message('Photo captured. Now sign below.')},'image/jpeg',.9)}
 function signed(){const c=$('signaturePad'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;for(let i=0;i<d.length;i+=4)if(d[i+3]&&d[i]<245)return true;return false}
 async function save(){try{const customerId=$('identityCustomer').value;if(!customerId)return message('Select a customer first.');if(!photoBlob)return message('Capture the live photo first.');if(!signed())return message('Please sign in the signature box.');const u=await current();if(!u)throw Error('Your login session has expired. Please sign in again.');const c=client(),base=`${u.id}/${customerId}/${Date.now()}`,photo=`${base}/photo.jpg`,sig=`${base}/signature.png`;message('Saving photo and signature...');let r=await c.storage.from('customer-identity').upload(photo,photoBlob,{contentType:'image/jpeg'});if(r.error)throw r.error;const sigBlob=await new Promise(ok=>$('signaturePad').toBlob(ok,'image/png'));r=await c.storage.from('customer-identity').upload(sig,sigBlob,{contentType:'image/png'});if(r.error)throw r.error;r=await c.from('customers').update({photo_path:photo,signature_path:sig,identity_captured_at:new Date().toISOString(),identity_captured_by:u.id}).eq('id',customerId).eq('created_by',u.id);if(r.error)throw r.error;message('✓ Customer photo and signature saved successfully.');stream?.getTracks().forEach(t=>t.stop());stream=null}catch(e){message('Save error: '+(e.message||e))}}
 function init(){if(!$('identityCustomer')||!window.supabase)return setTimeout(init,200);signature();loadCustomers();$('identityCustomer').addEventListener('focus',loadCustomers);$('startCamera').onclick=start;$('capturePhoto').onclick=capture;$('retakePhoto').onclick=()=>{photoBlob=null;$('photoPreview').classList.add('hidden');start()};$('saveIdentity').onclick=save;document.querySelector('[data-page="identity"]')?.addEventListener('click',()=>setTimeout(loadCustomers,150));}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();window.addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));
})();