/* OVAD AFRIKA - Standard Loan Offer Letter */
(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(n)||0);
 const client=()=>window.sb||window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
 let current=null;
 function ensureModal(){if(document.getElementById('offerLetterModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="offerLetterModal" class="offer-modal hidden"><div class="offer-toolbar"><button id="offerPrint" class="primary">🖨 Print</button><button id="offerPdf" class="primary">📄 Download PDF</button><button id="offerClose">Close</button></div><div id="offerLetterDocument" class="offer-document"></div></div>`);document.getElementById('offerClose').onclick=()=>document.getElementById('offerLetterModal').classList.add('hidden');document.getElementById('offerPrint').onclick=printLetter;document.getElementById('offerPdf').onclick=downloadPdf}
 async function getApplication(id){const c=client();const {data,error}=await c.from('loan_applications').select('*,customers(*),profiles!loan_applications_created_by_fkey(full_name,staff_grade)').eq('id',id).single();if(error)throw error;return data}
 function build(a){const c=a.customers||{};const today=new Date().toLocaleDateString('en-NG',{day:'2-digit',month:'long',year:'numeric'});const approval=a.final_decision_at?new Date(a.final_decision_at).toLocaleDateString('en-NG',{day:'2-digit',month:'long',year:'numeric'}):today;const officer=a.profiles||{};const monthly=a.monthly_repayment||0;return `<article class="offer-page"><header class="offer-header"><div><h1>OVAD AFRIKA</h1><p>LOAN OFFER LETTER</p></div><div class="offer-ref"><b>Date:</b> ${today}<br><b>Loan Reference:</b> ${esc(a.reference)}</div></header><p><b>${esc(c.full_name)}</b><br>${esc(c.residential_address||'')}</p><p>Dear ${esc(c.full_name)},</p><h2>RE: OFFER OF LOAN FACILITY</h2><p>We are pleased to inform you that <b>OVAD AFRIKA</b> has approved a loan facility for you subject to the terms and conditions contained in this letter and the applicable loan agreement.</p><table class="offer-table"><tr><th>Loan Product</th><td>${esc(a.product||a.loan_type||'Loan Facility')}</td></tr><tr><th>Purpose</th><td>${esc(a.purpose||'As stated in the loan application')}</td></tr><tr><th>Approved Amount</th><td><b>${money(a.amount)}</b></td></tr><tr><th>Interest Rate</th><td>${esc(a.annual_rate)}% per annum</td></tr><tr><th>Tenure</th><td>${esc(a.tenure)} months</td></tr><tr><th>Estimated Monthly Repayment</th><td><b>${money(monthly)}</b></td></tr><tr><th>Approval Date</th><td>${approval}</td></tr></table><h3>Terms and Conditions</h3><ol><li>The facility is subject to execution of the applicable loan agreement and completion of all required documentation.</li><li>Disbursement is subject to satisfactory completion of all conditions precedent and any required verification.</li><li>Repayments shall be made in accordance with the agreed repayment schedule.</li><li>Applicable fees, charges, security and other conditions shall be as stated in the loan agreement and applicable OVAD AFRIKA policies.</li><li>Late or missed repayments may attract applicable charges and may affect the customer's credit standing.</li><li>This offer is personal to the named customer and may not be transferred without written consent from OVAD AFRIKA.</li></ol><p>This offer letter should be read together with the formal loan agreement and other facility documentation. In the event of any inconsistency, the executed loan agreement shall prevail.</p><h3>Acceptance of Offer</h3><p>I, <b>${esc(c.full_name)}</b>, confirm that I have read, understood and accepted the above offer and agree to be bound by the applicable terms and conditions.</p><div class="signature-area"><div>____________________________<br><b>Customer Signature</b><br>Date: ________________________</div><div>____________________________<br><b>For: OVAD AFRIKA</b><br>Authorized Signatory<br>Date: ________________________</div></div><footer class="offer-footer">OVAD AFRIKA · Loan Reference ${esc(a.reference)} · Confidential</footer></article>`}
 async function open(id){try{ensureModal();const a=await getApplication(id);if(a.status!=='approved')return alert('Offer letters can only be generated for approved loans.');current=a;document.getElementById('offerLetterDocument').innerHTML=build(a);document.getElementById('offerLetterModal').classList.remove('hidden')}catch(e){alert('Unable to generate offer letter: '+e.message)}}
 function printLetter(){const html=document.getElementById('offerLetterDocument').innerHTML;const w=window.open('','_blank','width=900,height=1000');if(!w)return;w.document.write(`<html><head><title>OVAD AFRIKA - ${esc(current?.reference)}</title><style>${styles()}</style></head><body>${html}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),400)}
 async function downloadPdf(){if(!window.html2pdf){alert('PDF generator is still loading. Please try again in a moment.');return}const el=document.querySelector('#offerLetterDocument .offer-page');await window.html2pdf().set({margin:0.35,filename:`OVAD-AFRIKA-Offer-${current?.reference||'Loan'}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'in',format:'a4',orientation:'portrait'}}).from(el).save()}
 function styles(){return `.offer-page{font-family:Arial,sans-serif;color:#111;background:#fff;width:7.3in;min-height:10.3in;margin:auto;padding:.45in;box-sizing:border-box;font-size:11pt;line-height:1.45}.offer-header{display:flex;justify-content:space-between;border-bottom:3px solid #111;padding-bottom:14px;margin-bottom:24px}.offer-header h1{margin:0;font-size:25px;letter-spacing:1px}.offer-header p{margin:4px 0;font-weight:bold}.offer-ref{text-align:right;font-size:10pt}.offer-page h2{text-align:center;font-size:15pt;margin:22px 0}.offer-page h3{font-size:12pt;margin-top:20px}.offer-table{width:100%;border-collapse:collapse;margin:15px 0}.offer-table th,.offer-table td{border:1px solid #aaa;padding:8px;text-align:left}.offer-table th{width:42%}.signature-area{display:flex;justify-content:space-between;gap:30px;margin-top:45px}.offer-footer{margin-top:45px;padding-top:10px;border-top:1px solid #aaa;text-align:center;font-size:8pt}.offer-modal{position:fixed;inset:0;background:rgba(0,0,0,.65);z-index:9999;overflow:auto;padding:20px}.offer-toolbar{position:sticky;top:0;display:flex;gap:8px;justify-content:flex-end;background:#fff;padding:10px;margin:0 auto 15px;max-width:850px}.offer-document{background:#fff;max-width:850px;margin:auto;padding:20px}.hidden{display:none}@media print{.offer-toolbar{display:none}}`}
 function addStyle(){if(document.getElementById('offerLetterStyle'))return;const s=document.createElement('style');s.id='offerLetterStyle';s.textContent=styles();document.head.appendChild(s)}
 function addButtons(){if(!document.querySelector('#applications'))return;document.querySelectorAll('#applications tbody tr').forEach(row=>{if(row.querySelector('.offer-btn'))return;const cells=row.querySelectorAll('td');const text=row.innerText||'';if(!/Approved/i.test(text))return;const ref=(cells[0]?.innerText||'').trim();if(!ref)return;const cell=document.createElement('td');cell.innerHTML='<button class="offer-btn">Generate Offer Letter</button>';cell.querySelector('button').onclick=async()=>{const c=client();const {data}=await c.from('loan_applications').select('id').eq('reference',ref).single();if(data)open(data.id)};row.appendChild(cell)});const head=document.querySelector('#applications thead tr');if(head&&!head.querySelector('.offer-head')){const th=document.createElement('th');th.className='offer-head';th.textContent='Offer Letter';head.appendChild(th)}}
 addStyle();ensureModal();window.generateOfferLetter=open;setInterval(addButtons,1200);window.addEventListener('load',()=>setTimeout(addButtons,1000));
})();