const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(n)||0);let profile=null,customers=[],apps=[],audit=[];
const now=()=>new Date().toISOString(),ref=()=>`LA-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;
async function loadProfile(){const {data:{user}}=await sb.auth.getUser();if(!user){profile=null;return}const {data,error}=await sb.from('profiles').select('*').eq('id',user.id).single();if(error||!data){throw new Error('Your Supabase user exists, but no staff profile/role was found. Run the profile role SQL first.')}profile=data}
async function refresh(){if(!profile)return;const custQ=profile.role==='officer'?sb.from('customers').select('*').eq('created_by',profile.id).order('created_at',{ascending:false}):sb.from('customers').select('*').order('created_at',{ascending:false});const appQ=profile.role==='officer'?sb.from('loan_applications').select('*,customers(full_name)').eq('created_by',profile.id).order('created_at',{ascending:false}):sb.from('loan_applications').select('*,customers(full_name)').order('created_at',{ascending:false});const [c,a,l]=await Promise.all([custQ,appQ,sb.from('audit_logs').select('*,profiles(full_name)').order('created_at',{ascending:false})]);if(c.error)throw c.error;if(a.error)throw a.error;customers=c.data||[];apps=a.data||[];audit=l.data||[];renderAllUI()}
function status(a){return {draft:'Draft',pending_supervisor:'Awaiting Supervisor Review',approved:'Approved',declined:'Declined',returned:'Returned for Correction'}[a.status]||a.status}
function calcPayment(p,a,n){const r=a/1200;return !r?p/n:p*(r*Math.pow(1+r,n))/(Math.pow(1+r,n)-1)}function calcPrincipal(pay,a,n){const r=a/1200;return !r?pay*n:pay*(Math.pow(1+r,n)-1)/(r*Math.pow(1+r,n))}
async function log(appId,action,comment=''){await sb.from('audit_logs').insert({application_id:appId,action,comment,performed_by:profile.id})}
function setAuth(){const logged=!!profile;$('loginScreen').classList.toggle('hidden',logged);$('appShell').classList.toggle('hidden',!logged);if(!logged)return;$('userDisplay').textContent=`${profile.full_name} · ${profile.role}`;document.querySelectorAll('.officer-only').forEach(x=>x.style.display=profile.role==='officer'?'block':'none');document.querySelectorAll('.supervisor-only').forEach(x=>x.style.display=profile.role==='supervisor'||profile.role==='admin'?'block':'none');show('dashboard',false)}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';try{const {error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)throw error;await loadProfile();await refresh();setAuth()}catch(err){$('loginError').textContent=err.message||'Unable to sign in.'}};
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();profile=null;customers=[];apps=[];audit=[];setAuth()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));
function show(id,refreshIt=true){if(!profile)return;document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');if(refreshIt)refresh()}
$('kycForm').onsubmit=async e=>{e.preventDefault();try{const row={full_name:$('kycName').value,date_of_birth:$('kycDob').value||null,gender:$('kycGender').value,marital_status:$('kycMarital').value,phone:$('kycPhone').value,email:$('kycEmail').value,nin:$('kycNin').value,bvn:$('kycBvn').value,residential_address:$('kycAddress').value,employment_type:$('kycEmployment').value,employer_or_business:$('kycEmployer').value,job_or_business_type:$('kycJob').value,monthly_income:+$('kycIncome').value,monthly_expenses:+$('kycExpenses').value,next_of_kin:{name:$('nokName').value,relationship:$('nokRelationship').value,phone:$('nokPhone').value,address:$('nokAddress').value},created_by:profile.id};const {data,error}=await sb.from('customers').insert(row).select().single();if(error)throw error;await log(null,'Customer KYC created',data.full_name);$('kycForm').reset();alert('Customer KYC saved.');await refresh()}catch(err){alert(err.message)}};
$('applicationForm').onsubmit=async e=>{e.preventDefault();try{const c=customers.find(x=>x.id===$('appCustomer').value);if(!c)throw Error('Select a customer');const row={reference:ref(),customer_id:c.id,loan_type:$('appType').value,product:$('appProduct').value,purpose:$('appPurpose').value,amount:+$('appAmount').value,tenure:+$('appTenure').value,annual_rate:+$('appRate').value,existing_monthly_debt:+$('appDebt').value,collateral_description:$('appCollateralDesc').value,collateral_value:+$('appCollateral').value,guarantor_name:$('appGuarantor').value,guarantor_phone:$('appGuarantorPhone').value,created_by:profile.id,status:'draft'};const {data,error}=await sb.from('loan_applications').insert(row).select().single();if(error)throw error;await log(data.id,'Loan application created',`${c.full_name} requested ${money(row.amount)}`);$('applicationForm').reset();alert('Loan application saved.');await refresh();show('appraisal',false)}catch(err){alert(err.message)}};
$('appraisalForm').onsubmit=async e=>{e.preventDefault();try{const a=apps.find(x=>x.id===$('appraisalApplication').value),c=customers.find(x=>x.id===a.customer_id);if(!a||!c)throw Error('Select an application');const cash=Number(c.monthly_income)-Number(c.monthly_expenses)-Number(a.existing_monthly_debt),dr=c.monthly_income?Number(a.existing_monthly_debt)/Number(c.monthly_income)*100:100,coll=a.amount?Number(a.collateral_value)/Number(a.amount)*100:0;let score=(calcPayment(a.amount,a.annual_rate,a.tenure)<=cash*.4?40:calcPayment(a.amount,a.annual_rate,a.tenure)<=cash*.6?28:calcPayment(a.amount,a.annual_rate,a.tenure)<=cash?15:0)+(dr<=20?20:dr<=35?15:dr<=50?8:0)+Number($('stability').value)+(coll>=100?15:coll>=70?11:coll>=40?6:0)+Number($('credit').value);score=Math.min(100,Math.round(score));const recommended=$('overrideRecommended').value?Math.min(+$('overrideRecommended').value,a.amount):Math.max(0,Math.min(a.amount,calcPrincipal(Math.max(cash*.4,0),a.annual_rate,a.tenure)));const {error}=await sb.from('loan_applications').update({recommended_amount:recommended,monthly_repayment:calcPayment(recommended,a.annual_rate,a.tenure),available_cash_flow:cash,appraisal_score:score,appraisal_decision:score>=75?'recommended':score>=50?'review':'not recommended',appraisal_notes:$('appraisalNotes').value,status:'pending_supervisor',appraised_by:profile.id,appraised_at:now()}).eq('id',a.id);if(error)throw error;await log(a.id,'Appraisal completed and submitted',`Score ${score}/100`);$('appraisalForm').reset();alert('Submitted to Supervisor.');await refresh();show('applications',false)}catch(err){alert(err.message)}};
window.finalDecision=async(id,decision)=>{const a=apps.find(x=>x.id===id);if(!a)return;const comment=prompt(decision==='approved'?'Approval comment (optional):':decision==='returned'?'Reason for return:':'Reason for decline:')||'';try{const {error}=await sb.from('loan_applications').update({status:decision,supervisor_id:profile.id,supervisor_comment:comment,final_decision_at:now()}).eq('id',id);if(error)throw error;await log(id,`Supervisor ${decision}`,comment);await refresh()}catch(err){alert(err.message)}};
function renderCustomers(){$('customerList').innerHTML=customers.map(c=>`<tr><td>${c.full_name}</td><td>${c.phone}</td><td>${money(c.monthly_income)}</td><td>${new Date(c.created_at).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="4">No customers saved.</td></tr>';$('appCustomer').innerHTML='<option value="">Select customer</option>'+customers.map(c=>`<option value="${c.id}">${c.full_name} — ${c.phone}</option>`).join('')}
function renderAppraisalOptions(){$('appraisalApplication').innerHTML='<option value="">Select application</option>'+apps.filter(a=>a.status==='draft'||a.status==='returned').map(a=>`<option value="${a.id}">${a.reference} — ${a.customers?.full_name||''}</option>`).join('')}
function render(){const visible=apps;$('total').textContent=visible.length;$('pending').textContent=visible.filter(a=>a.status==='pending_supervisor').length;$('approved').textContent=visible.filter(a=>a.status==='approved').length;$('declined').textContent=visible.filter(a=>['declined','returned'].includes(a.status)).length;$('recent').innerHTML=visible.slice(0,6).map(a=>`<tr><td>${a.reference}</td><td>${a.customers?.full_name||''}</td><td>${a.loan_type}</td><td>${money(a.amount)}</td><td>${status(a)}</td></tr>`).join('')||'<tr><td colspan="5">No applications yet.</td></tr>'}
function renderApps(){$('all').innerHTML=apps.map(a=>`<tr><td>${a.reference}</td><td>${a.customers?.full_name||''}</td><td>${a.loan_type}</td><td>${money(a.amount)}</td><td>${money(a.recommended_amount)}</td><td>${a.appraisal_score}/100</td><td>${status(a)}</td></tr>`).join('')||'<tr><td colspan="7">No applications saved.</td></tr>'}
function renderQueue(){$('approvalQueue').innerHTML=apps.filter(a=>a.status==='pending_supervisor').map(a=>`<tr><td>${a.reference}</td><td>${a.customers?.full_name||''}</td><td>${money(a.amount)}</td><td>${money(a.recommended_amount)}</td><td>${a.appraisal_score}/100</td><td><button onclick="finalDecision('${a.id}','approved')">Approve</button><button onclick="finalDecision('${a.id}','declined')">Decline</button><button onclick="finalDecision('${a.id}','returned')">Return</button></td></tr>`).join('')||'<tr><td colspan="6">No applications awaiting approval.</td></tr>'}
function renderAudit(){$('auditList').innerHTML=audit.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${x.application_id||'—'}</td><td>${x.action}</td><td>${x.profiles?.full_name||'—'}</td><td>${x.comment||'—'}</td></tr>`).join('')||'<tr><td colspan="5">No audit records yet.</td></tr>'}
function report(){const n=apps.length,req=apps.reduce((s,a)=>s+Number(a.amount),0),rec=apps.reduce((s,a)=>s+Number(a.recommended_amount),0),avg=n?apps.reduce((s,a)=>s+Number(a.appraisal_score),0)/n:0,ap=apps.filter(a=>a.status==='approved').length;$('reqTotal').textContent=money(req);$('recTotal').textContent=money(rec);$('avgScore').textContent=avg.toFixed(1);$('approvalRate').textContent=n?(ap/n*100).toFixed(1)+'%':'0%'}
function renderAllUI(){render();renderCustomers();renderAppraisalOptions();renderApps();renderQueue();renderAudit();report()}
(async()=>{try{await loadProfile();if(profile){await refresh();setAuth()}}catch(err){console.error(err);$('loginError').textContent=err.message}})();