// LoanAppraise guided workflow: normal flow + robust returned-correction entry point.
(()=>{
 const KEY='loanappraise_returned_session';
 const go=p=>document.querySelector(`[data-page="${p}"]`)?.click();
 const apps=()=>window.apps||[];
 const find=id=>apps().find(a=>String(a.id)===String(id));
 const set=(id,v)=>{const e=document.getElementById(id);if(e&&v!==undefined&&v!==null)e.value=v};
 const saveSession=a=>{const c=a?.customers||{};if(!a)return null;const s={applicationId:a.id,customerId:a.customer_id||c.id,reference:a.reference||'',customerName:c.full_name||'',requested:a.amount||0,recommended:a.recommended_amount||0,tenure:a.tenure||12,rate:a.annual_rate||25,debt:a.existing_monthly_debt||0,reason:a.supervisor_comment||a.return_reason||a.decision_comment||''};localStorage.setItem(KEY,JSON.stringify(s));window.returnedApplicationSession=s;window.editAppId=a.id;window.editCustomerId=s.customerId;return s};
 const session=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
 function hydrate(a,s){if(!a)return;const c=a.customers||{};set('appCustomer',s.customerId);set('identityCustomer',s.customerId);set('appraisalApplication',a.id);set('appType',a.type||a.loan_type||'Personal');set('appProduct',a.product||'');set('appPurpose',a.purpose||'');set('appAmount',a.amount??'');set('appTenure',a.tenure??12);set('appRate',a.rate??a.annual_rate??25);set('appDebt',a.debt??a.existing_monthly_debt??0);set('appCollateralDesc',a.collateral_desc??a.collateral_description??'');set('appCollateral',a.collateral_value??0);set('appGuarantor',a.guarantor_name??'');set('appGuarantorPhone',a.guarantor_phone??'');set('overrideRecommended',a.recommended_amount??s.recommended??'');set('appraisalNotes',a.appraisal_notes??'');const k={kycName:c.full_name,kycDob:c.date_of_birth,kycGender:c.gender||'Male',kycMarital:c.marital_status||'Single',kycPhone:c.phone,kycEmail:c.email,kycNin:c.nin,kycBvn:c.bvn,kycAddress:c.residential_address||c.address,kycEmployment:c.employment_type||'Salaried',kycEmployer:c.employer_or_business,kycJob:c.job_or_business_type,kycIncome:c.monthly_income??c.income,kycExpenses:c.monthly_expenses??c.expenses};Object.entries(k).forEach(([id,v])=>set(id,v));const n=c.next_of_kin||{};set('nokName',n.name);set('nokRelationship',n.relationship);set('nokPhone',n.phone);set('nokAddress',n.address)}
 function startCorrection(id){const a=find(id);if(!a){alert('Returned application could not be loaded. Please refresh the page.');return false}const s=saveSession(a);hydrate(a,s);document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const page=document.getElementById('customers');if(page)page.classList.add('active');return false}
 window.startCorrection=startCorrection;
 function extractId(el){let x=el;for(let i=0;i<5&&x;i++,x=x.parentElement){for(const attr of ['data-application-id','data-app-id','data-id']){const v=x.getAttribute?.(attr);if(v)return v}const oc=x.getAttribute?.('onclick')||'';let m=oc.match(/startCorrection\s*\(\s*['\"]?([^'\")\s]+)['\"]?\s*\)/);if(m)return m[1]}return null}
 document.addEventListener('click',e=>{const el=e.target.closest?.('button,a,[role="button"]');if(!el)return;const text=(el.textContent||'').toLowerCase();if(text.includes('correct complete file')||text.includes('start correction')||text.includes('correction')){const id=extractId(el);if(id){e.preventDefault();e.stopImmediatePropagation();startCorrection(id)}}},true);
 function returnedHydrate(){const s=session();if(!s?.applicationId)return;const a=find(s.applicationId);if(!a)return;hydrate(a,s)}
 function wire(){const k=document.getElementById('kycForm');if(k&&!k.dataset.workflow){k.dataset.workflow='1';k.addEventListener('submit',()=>setTimeout(()=>{const id=window.editCustomerId||document.getElementById('appCustomer')?.value;if(id)localStorage.setItem('loanappraise_current_customer',id);go('identity')},700))}const i=document.getElementById('saveIdentity');if(i&&!i.dataset.workflow){i.dataset.workflow='1';i.addEventListener('click',()=>setTimeout(()=>{const id=document.getElementById('identityCustomer')?.value;if(id)localStorage.setItem('loanappraise_current_customer',id);go('application')},900))}const a=document.getElementById('applicationForm');if(a&&!a.dataset.workflow){a.dataset.workflow='1';a.addEventListener('submit',()=>setTimeout(()=>go('appraisal'),700))}returnedHydrate()}
 document.addEventListener('DOMContentLoaded',wire);setInterval(wire,1000);
})();