(function(){
  const money=v=>'₦'+(Number(v||0)||0).toLocaleString('en-NG',{maximumFractionDigits:0});
  const num=v=>Number(String(v??'').replace(/,/g,''))||0;
  function renderProducts(){
    const form=document.querySelector('.form');
    if(!form || !form.innerHTML.includes('Product rows will calculate gross profit')) return;
    const existing=JSON.parse(localStorage.getItem('loanappraise_products')||'[]');
    form.querySelector('.card').innerHTML='<h3>Products / Trading Lines</h3><p class="muted">Add the main products or services sold by the customer. Gross profit and margin calculate automatically.</p><div id="productsRows"></div><button type="button" class="secondary" id="addProduct">+ Add Product</button><div class="cards" style="margin-top:16px"><div class="card"><small>Total Sales</small><div class="stat" id="productSales">₦0</div></div><div class="card"><small>Total Cost</small><div class="stat" id="productCost">₦0</div></div><div class="card"><small>Gross Profit</small><div class="stat" id="productProfit">₦0</div></div><div class="card"><small>Gross Margin</small><div class="stat" id="productMargin">0%</div></div></div>';
    const rows=document.getElementById('productsRows');
    function totals(){let sales=0,cost=0;rows.querySelectorAll('.product-row').forEach(r=>{sales+=num(r.querySelector('[data-p="sales"]').value);cost+=num(r.querySelector('[data-p="cost"]').value)});const profit=sales-cost;document.getElementById('productSales').textContent=money(sales);document.getElementById('productCost').textContent=money(cost);document.getElementById('productProfit').textContent=money(profit);document.getElementById('productMargin').textContent=(sales?((profit/sales)*100).toFixed(1):'0')+'%';localStorage.setItem('loanappraise_products',JSON.stringify([...rows.querySelectorAll('.product-row')].map(r=>({name:r.querySelector('[data-p="name"]').value,sales:num(r.querySelector('[data-p="sales"]').value),cost:num(r.querySelector('[data-p="cost"]').value)}))))}
    function add(p={}){const r=document.createElement('div');r.className='product-row card';r.style.marginBottom='12px';r.innerHTML='<div class="grid"><div class="field"><label>Product / Service</label><input data-p="name" value=""></div><div class="field"><label>Monthly Sales</label><input data-p="sales" inputmode="numeric" value=""></div><div class="field"><label>Monthly Cost</label><input data-p="cost" inputmode="numeric" value=""></div><div class="field"><label>Gross Profit</label><input data-p="profit" readonly value="₦0"></div><div class="field"><label>Gross Margin</label><input data-p="margin" readonly value="0%"></div></div><button type="button" class="secondary removeProduct">Remove</button>';r.querySelector('[data-p="name"]').value=p.name||'';r.querySelector('[data-p="sales"]').value=p.sales?Number(p.sales).toLocaleString('en-NG'):'';r.querySelector('[data-p="cost"]').value=p.cost?Number(p.cost).toLocaleString('en-NG'):'';function calcRow(){const s=num(r.querySelector('[data-p="sales"]').value),c=num(r.querySelector('[data-p="cost"]').value),g=s-c;r.querySelector('[data-p="profit"]').value=money(g);r.querySelector('[data-p="margin"]').value=(s?((g/s)*100).toFixed(1):'0')+'%';totals()}r.querySelectorAll('[data-p="sales"],[data-p="cost"]').forEach(x=>x.addEventListener('input',()=>{x.value=x.value.replace(/[^0-9,]/g,'');calcRow()}));r.querySelector('.removeProduct').onclick=()=>{r.remove();totals()};rows.appendChild(r);calcRow()}
    existing.forEach(add);if(!rows.children.length)add();document.getElementById('addProduct').onclick=()=>add();
    const next=document.getElementById('next');if(next&&!next.dataset.productsHook){next.dataset.productsHook='1';next.addEventListener('click',()=>{totals()},{capture:true})}
    totals();
  }
  const obs=new MutationObserver(()=>renderProducts());obs.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setTimeout(renderProducts,100);
})();
