/* LoanAppraise 2.0 persistence aligned with the live loan_applications schema. */
(function(){'use strict';
function ref(){return 'LA-'+Date.now().toString(36).toUpperCase();}
window.LoanAppraiseDB={
 async saveDraft(client,user,form){return persist(client,user,form,'draft');},
 async submit(client,user,form){return persist(client,user,form,'pending_supervisor');},
 async mine(client,user){if(!client||!user)throw new Error('Not authenticated');const {data,error}=await client.from('loan_applications').select('*').eq('created_by',user.id).order('updated_at',{ascending:false});if(error)throw error;return data||[];}
};
async function persist(client,user,form,status){if(!client||!user)throw new Error('Not authenticated');const c=form.customer||{},l=form.loan||{},b=form.business||{},f=form.financials||{},col=form.collateral||{};let customerId=form.customer_id||null;
 if(!customerId){const customer={full_name:c.full_name||'Unnamed Customer',phone:c.phone||'',email:c.email||null,nin:c.nin||null,bvn:c.bvn||null,residential_address:c.residential_address||null,employment_type:c.employment_type||null,employer_or_business:b.business_name||c.employer_or_business||null,job_or_business_type:b.business_type||c.job_or_business_type||null,monthly_income:Number(c.monthly_income)||0,monthly_expenses:Number(c.monthly_expenses)||0,created_by:user.id};const r=await client.from('customers').insert(customer).select('id').single();if(r.error)throw r.error;customerId=r.data.id;form.customer_id=customerId;}
 const payload={reference:form.reference||ref(),customer_id:customerId,loan_type:l.loan_type||l.loan_product||'Business Loan',product:l.product||l.loan_product||'Standard',purpose:l.purpose||null,amount:Number(l.amount)||0,tenure:Number(l.tenure)||0,annual_rate:Number(l.annual_rate)||0,existing_monthly_debt:Number(l.existing_monthly_debt)||0,collateral_description:col.description||col.collateral_type||null,collateral_value:Number(col.market_value)||0,guarantor_name:col.guarantor_name||null,guarantor_phone:col.guarantor_phone||null,recommended_amount:0,monthly_repayment:Number(l.monthly_repayment)||0,available_cash_flow:Number(f.available_cash_flow)||0,appraisal_score:0,status,created_by:user.id,updated_at:new Date().toISOString(),submitted_at:status==='pending_supervisor'?new Date().toISOString():undefined};
 let q;if(form.application_id){q=client.from('loan_applications').update(payload).eq('id',form.application_id).eq('created_by',user.id).select().single()}else{q=client.from('loan_applications').insert(payload).select().single()}const r=await q;if(r.error)throw r.error;if(r.data?.id){form.application_id=r.data.id;form.reference=r.data.reference}return r.data;
}
})();